site_name: DK Tech Base
site_url: https://dkang919.github.io/my-tech-base/
repo_url: https://github.com/dkang919/my-tech-base
repo_name: GitHub

theme:
  name: material
  palette: 
    scheme: default # or slate (다크모드)
  features:
    - navigation.tabs # 상단 탭 메뉴
    - navigation.sections
    - content.code.copy # 코드 복사 버튼

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # 참고/경고 박스 사용 가능