site_name: DK Tech Base
site_url: https://dkang919.github.io/tech-base/
repo_url: https://github.com/dkang919/tech-base
repo_name: GitHub

theme:
  name: material
  palette: 
    - scheme: default # 라이트 모드
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # 다크 모드theme:
  name: material
  # (기존 palette 설정 유지하되, 아래 속성 추가)
  palette: 
    - scheme: default
      primary: teal   # 추천: teal, indigo, slate, black
      accent: purple  # 버튼 등 포인트 컬러
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs # 상단 탭 메뉴 (프로페셔널한 느낌)
    - navigation.sections
    - navigation.top # 위로 가기 버튼
    - content.code.copy # 코드 복사 버튼

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition            # [필수] 박스 기능
  - pymdownx.details      # [필수] 접었다 폈다 하는 기능
  - pymdownx.arithmatex:  # [필수] 수식 기능 ($E=mc^2$)
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Projects:
      - Canada IEC Monitor: projects/iec-monitor.md
      - Canada PC Parts Tracker: projects/ca-pc-parts-tracker.md
  - Quiz:
      - Flash Cards: quiz/ml-quiz.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dkang919
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/danielkdw/
    - icon: fontawesome/solid/envelope
      link: mailto:kangd1990@gmail.com